import { writeFile } from 'node:fs/promises'
import type { Conversation } from '@shared/types'

/** Human friendly, portable Markdown export of one or more conversations. */
export function conversationsToMarkdown(conversations: Conversation[], appVersion: string): string {
  const lines: string[] = [
    `# GPTN export`,
    ``,
    `Generated by GPTN ${appVersion} on ${new Date().toLocaleString()}`,
    `Conversations: ${conversations.length}`,
    ``
  ]

  for (const conversation of conversations) {
    lines.push(`---`, ``, `## ${conversation.title}`, ``)
    lines.push(
      `*Model: ${conversation.model} · Created: ${new Date(conversation.createdAt).toLocaleString()} · Updated: ${new Date(
        conversation.updatedAt
      ).toLocaleString()}*`,
      ``
    )
    for (const message of conversation.messages) {
      lines.push(message.role === 'user' ? `### You` : `### GPTN`, ``)
      if (message.error) lines.push(`> ${message.error.title}: ${message.error.message}`, ``)
      lines.push(message.content.trim() || '*(empty)*', ``)
    }
  }
  return lines.join('\n')
}

export function conversationsToJson(conversations: Conversation[], appVersion: string): string {
  return JSON.stringify(
    {
      app: 'GPTN',
      appVersion,
      schemaVersion: 1,
      exportedAt: new Date().toISOString(),
      conversations
    },
    null,
    2
  )
}

export async function writeExport(path: string, content: string): Promise<void> {
  await writeFile(path, content, 'utf8')
}

/** Sanitises a conversation title for use as a file name. */
export function fileNameFor(title: string, extension: string): string {
  const safe = title
    .replace(/[^\p{L}\p{N}\s._-]/gu, '')
    .replace(/\s+/g, '-')
    .slice(0, 60)
    .replace(/^-+|-+$/g, '')
  return `${safe || 'gptn-chat'}.${extension}`
}
